//SELECTION SORT - MELHOR CASO: O(n^2), MEDIO CASO: O(n^2), PIOR CASO: O(n^2)

//BUBBLE SORT - MELHOR CASO: O(n), MEDIO CASO: O(n^2), PIOR CASO: O(n^2)

//INSERTION SORT - MELHOR CASO: O(n), MEDIO CASO: O(n^2), PIOR CASO: O(n^2)

//MERGE SORT - MELHOR CASO: O(n log n), MEDIO CASO: O(n log n), PIOR CASO: O(n log n)